// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaU05XEmIIv4BmWm5q81VrxHo_4yU-wTU',
    appId: '1:222750546701:android:a3bccc661ca3b335122e44',
    messagingSenderId: '222750546701',
    projectId: 'smart-routes-f91a3',
    storageBucket: 'smart-routes-f91a3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3bC_kl_xOw-650tMz-YheMPUhW-QDP0U',
    appId: '1:222750546701:ios:d57fedac73d1fe6a122e44',
    messagingSenderId: '222750546701',
    projectId: 'smart-routes-f91a3',
    storageBucket: 'smart-routes-f91a3.firebasestorage.app',
    iosBundleId: 'com.smartRoutes',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3F2l3hhSp2ESBTDRzrM2IkWF3j8SpjFE',
    appId: '1:222750546701:web:32c2d7ed4811b406122e44',
    messagingSenderId: '222750546701',
    projectId: 'smart-routes-f91a3',
    authDomain: 'smart-routes-f91a3.firebaseapp.com',
    storageBucket: 'smart-routes-f91a3.firebasestorage.app',
    measurementId: 'G-4DLLY31NP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3bC_kl_xOw-650tMz-YheMPUhW-QDP0U',
    appId: '1:222750546701:ios:d57fedac73d1fe6a122e44',
    messagingSenderId: '222750546701',
    projectId: 'smart-routes-f91a3',
    storageBucket: 'smart-routes-f91a3.firebasestorage.app',
    iosBundleId: 'com.smartRoutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3F2l3hhSp2ESBTDRzrM2IkWF3j8SpjFE',
    appId: '1:222750546701:web:74d49570955c1db7122e44',
    messagingSenderId: '222750546701',
    projectId: 'smart-routes-f91a3',
    authDomain: 'smart-routes-f91a3.firebaseapp.com',
    storageBucket: 'smart-routes-f91a3.firebasestorage.app',
    measurementId: 'G-TNFVH6RHK9',
  );
}
